# Generated by Django 3.1.3 on 2023-06-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='question text', max_length=100),
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='question text', max_length=500),
        ),
    ]
